dataset_path: jungypark/ME2
dataset_kwargs:
  token: True
task: "ME2_ps"
test_split: train
output_type: generate_until
doc_to_visual: !function utils.doc_to_visual
doc_to_text: !function utils.doc_to_text
doc_to_target: answer_text
generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function utils.ME2_process_results_problem_solving
metric_list:
  - metric: toy_task
    aggregation : !function utils.ME2_ps
    higher_is_better : true
  - metric: toy_task_GE
    aggregation : !function utils.ME2_ps_GE
    higher_is_better : true
  - metric: toy_task_GR
    aggregation : !function utils.ME2_ps_GR
    higher_is_better : true
lmms_eval_specific_kwargs:
  default:
    task: 0
metadata:
  - version: 0.0