dataset_path: jungypark/ME2
dataset_kwargs:
  token: True
task: "ME2_figure_caption"
test_split: train
output_type: generate_until
doc_to_visual: !function utils.doc_to_visual
doc_to_text: !function utils.doc_to_text
doc_to_target: visual_key_points
generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function utils.ME2_process_results_captioning
metric_list:
  - metric: Caption_f1
    aggregation : !function utils.ME2_Caption_MCQA
    higher_is_better : true
  - metric: Caption_precision
    aggregation : !function utils.ME2_Caption_MCQA_GE
    higher_is_better : true
  - metric: Caption_recall
    aggregation : !function utils.ME2_Caption_MCQA_GR
    higher_is_better : true
lmms_eval_specific_kwargs:
  default:
    task: 1
metadata:
  - version: 0.0